name: 夜間テスト実行

on:
  schedule:
    # 毎日午前2時（UTC）に実行 = 日本時間午前11時
    - cron: "0 18 * * *"

  # 手動実行も可能に
  workflow_dispatch:

jobs:
  full-test-suite:
    name: "完全テストスイート"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.51.1-noble
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Build application
        run: npm run build

      - name: Start application
        run: |
          npm run start -- -p 9999 &
          echo "アプリケーションの起動を待機中..."
          sleep 60
          npx wait-on http://localhost:9999 -t 60000

      - name: Run all tests
        id: playwright
        run: |
          # すべてのテストを実行
          npx playwright test --project=webkit-headless
        env:
          CI: true
          PLAYWRIGHT_TEST_BASE_URL: http://localhost:9999
          HOME: /root

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Notify test results
        if: always()
        run: |
          if [ "${{ steps.playwright.outputs.status }}" == "0" ]; then
            echo "テスト成功: ${{ steps.playwright.outputs.date }}"
          else
            echo "テスト失敗: ${{ steps.playwright.outputs.date }}"
          fi
