name: Playwright テスト

on:
  pull_request:
    branches: [main, master, develop]
  # 手動実行用のトリガー
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.51.1-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
        # キャッシュパスを明示的に指定
          cache-dependency-path: '**/package-lock.json'

      - name: 依存関係のインストール
        run: npm ci

      # 環境変数を設定ファイルに書き出し
      - name: 環境変数の設定
        run: |
          echo "PORT=3000" > .env.local
          echo "HOST=localhost" >> .env.local
          echo "環境変数を設定しました:"
          cat .env.local

      - name: テスト環境の起動
        run: |
          # ホストを 0.0.0.0 に設定して、すべてのネットワークインターフェースでリッスン
          # サーバーを起動し、バックグラウンドで実行
          nohup npm run dev --hostname=0.0.0.0 > nohup.out 2>&1 &
          echo "Webサーバーを起動しました"

      - name: Playwright テストの実行
        run: |
          # テスト実行時にベースURLを明示的に指定
          npm run test:chrome-headless -- --timeout=60000
        env:
          # テストに必要な環境変数
          NODE_ENV: test
      - name: HTMLレポートをアーティファクトとしてアップロード
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.run_id }}
          path: playwright-report/
          retention-days: 30
      - name: テスト結果をPRコメントとして追加
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            try {
              // テスト結果のサマリーを読み込む
              let summary = '';
              if (fs.existsSync('./playwright-report/results.json')) {
                const results = JSON.parse(fs.readFileSync('./playwright-report/results.json', 'utf8'));
                
                // 簡単なサマリーを作成
                const total = results.stats?.total || 0;
                const passed = results.stats?.passed || 0;
                const failed = results.stats?.failed || 0;
                const skipped = results.stats?.skipped || 0;
                
                summary = `### Playwright テスト結果
                - 合計テスト数: ${total}
                - 成功: ${passed}
                - 失敗: ${failed}
                - スキップ: ${skipped}
                
                テスト詳細は GitHub Actions の "Artifacts" セクションからダウンロードできます。
                `;
              } else {
                summary = '### Playwright テスト完了\nテスト詳細は GitHub Actions の "Artifacts" セクションからダウンロードできます。';
              }
              
              // PRへコメントを追加
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: summary
              });
            } catch (error) {
              console.error('Error creating PR comment:', error);
            }
